export const banksData: Record<string, string[]> = {
  "United States": [
    "JPMorgan Chase",
    "Bank of America",
    "Wells Fargo",
    "Citibank",
    "US Bank",
    "PNC Bank",
    "Bank of New York Mellon",
    "Capital One",
    "TD Bank",
    "Ally Bank",
  ],
  "United Kingdom": [
    "HSBC",
    "Barclays",
    "NatWest",
    "Lloyds",
    "Standard Chartered",
    "Bank of Scotland",
    "Santander UK",
    "TSB Bank",
    "Metro Bank",
    "Revolut",
  ],
  "Canada": [
    "Royal Bank of Canada",
    "Toronto-Dominion Bank",
    "Bank of Nova Scotia",
    "Bank of Montreal",
    "CIBC",
    "National Bank of Canada",
    "Tangerine Bank",
    "Scotiabank",
  ],
  "Australia": [
    "Commonwealth Bank",
    "Westpac",
    "ANZ",
    "NAB",
    "ING Australia",
    "Macquarie Bank",
    "Bank of Queensland",
    "AMP Bank",
  ],
  "Germany": [
    "Deutsche Bank",
    "Commerzbank",
    "DZ Bank",
    "HypoVereinsbank",
    "Sparkasse",
    "Comdirect",
    "ING-DiBa",
    "Postbank",
  ],
  "France": [
    "BNP Paribas",
    "Crédit Agricole",
    "Société Générale",
    "Banque de France",
    "Natixis",
    "BPCE",
    "Crédit Mutuel",
    "La Banque Postale",
  ],
  "Japan": [
    "Mitsubishi UFJ Financial Group",
    "Sumitomo Mitsui Financial Group",
    "Mizuho Financial Group",
    "Nomura Holdings",
    "SMBC",
    "Bank of Tokyo-Mitsubishi UFJ",
    "Sony Bank",
    "Rakuten Bank",
  ],
  "China": [
    "Industrial and Commercial Bank of China",
    "China Construction Bank",
    "Bank of China",
    "Agricultural Bank of China",
    "Bank of Communications",
    "China Merchants Bank",
    "Shanghai Pudong Development Bank",
    "China Minsheng Bank",
  ],
  "India": [
    "State Bank of India",
    "HDFC Bank",
    "ICICI Bank",
    "Axis Bank",
    "Kotak Mahindra Bank",
    "Punjab National Bank",
    "Bank of Baroda",
    "Federal Bank",
  ],
  "Singapore": [
    "DBS Bank",
    "OCBC Bank",
    "UOB",
    "Citibank Singapore",
    "HSBC Singapore",
    "Bank of China",
    "Standard Chartered",
    "Maybank",
  ],
  "Hong Kong": [
    "HSBC",
    "Standard Chartered",
    "Bank of China",
    "Bank of East Asia",
    "Hang Seng Bank",
    "DBS Hong Kong",
    "Citibank",
    "Mizuho Bank",
  ],
  "Mexico": [
    "BBVA México",
    "Santander México",
    "Scotiabank",
    "HSBC México",
    "Banorte",
    "Banco Azteca",
    "Banco Inbursa",
    "American Express Bank",
  ],
  "Brazil": [
    "Banco do Brasil",
    "Bradesco",
    "Caixa Econômica Federal",
    "Itaú Unibanco",
    "Santander Brasil",
    "Banco Safra",
    "HSBC Brasil",
    "BTG Pactual",
  ],
  "South Korea": [
    "KB Financial Group",
    "Shinhan Bank",
    "Hana Bank",
    "Woori Bank",
    "National Bank of Korea",
    "Korea Development Bank",
    "Korean Exchange Bank",
    "Busan Bank",
  ],
  "United Arab Emirates": [
    "Emirates NBD",
    "ADIB",
    "First Abu Dhabi Bank",
    "ADCB",
    "DIB",
    "FAB",
    "RAKBANK",
    "Mashreq Bank",
  ],
  "Saudi Arabia": [
    "Saudi National Bank",
    "Al Rajhi Bank",
    "Riyad Bank",
    "Saudi British Bank",
    "Bank AlJazira",
    "Arab National Bank",
    "Banque Saudi Fransi",
  ],
  "Switzerland": [
    "UBS",
    "Credit Suisse",
    "Raiffeisen Bank",
    "Cantonal Banks",
    "Zürcher Kantonalbank",
    "ZKB",
    "Bank Cler",
  ],
  "Netherlands": [
    "ABN AMRO",
    "ING Netherlands",
    "Rabobank",
    "SNS Bank",
    "ASN Bank",
    "BNG Bank",
    "Triodos Bank",
  ],
  "Spain": [
    "CaixaBank",
    "Banco Santander",
    "BBVA",
    "Banc Sabadell",
    "Bankia",
    "Abanca",
    "Unicaja",
  ],
  "Italy": [
    "Intesa Sanpaolo",
    "UniCredit",
    "Banco BPM",
    "Banco Popolare",
    "Monte dei Paschi",
    "Mediobanca",
    "Banca Generali",
  ],
  "Sweden": [
    "SEB",
    "Nordea",
    "Swedbank",
    "Handelsbanken",
    "Danske Bank",
    "Länsförsäkringar",
    "SBAB",
  ],
  "Norway": [
    "DNB ASA",
    "Nordea",
    "Danske Bank",
    "Sparebanken 1",
    "Sparebank 1 Nord",
    "Norwegian Bank",
  ],
  "Denmark": [
    "Danske Bank",
    "Nordea",
    "Sydbank",
    "Jyske Bank",
    "Spar Nord",
    "Nykredit",
  ],
  "Poland": [
    "PKO Bank Polski",
    "Bank Zachodni WBK",
    "ING Bank Śląski",
    "BNP Paribas Bank Polska",
    "Santander Bank Polska",
    "Millennium Bank",
    "BGK",
  ],
  "Czech Republic": [
    "Česká spořitelna",
    "Komercční banka",
    "ČSOB",
    "ING Bank",
    "UniCredit Bank",
    "Raiffeisenbank",
  ],
  "Russia": [
    "Sberbank",
    "VTB",
    "Gazprombank",
    "Alfa-Bank",
    "Raiffeisen Bank Russia",
    "Unicredit Bank",
  ],
  "Turkey": [
    "Ziraat Bankası",
    "İş Bankası",
    "Halkbank",
    "Vakıfbank",
    "Garanti Bank",
    "Akbank",
    "Şekerbank",
  ],
  "Thailand": [
    "Siam Commercial Bank",
    "Bangkok Bank",
    "Kasikornbank",
    "Bank of Ayudhya",
    "CIMB Thai",
    "TBANK",
    "Krung Thai Bank",
  ],
  "Malaysia": [
    "Maybank",
    "CIMB Bank",
    "HSBC Bank Malaysia",
    "Bank Negara Malaysia",
    "Public Bank",
    "RHB Bank",
    "AmBank",
  ],
  "Indonesia": [
    "Bank Mandiri",
    "Bank Rakyat Indonesia",
    "Bank Central Asia",
    "Bank Negara Indonesia",
    "CIMB Niaga",
    "Bank OCBC NISP",
    "Bank Danamon",
  ],
  "Philippines": [
    "BDO Unibank",
    "Bank of the Philippine Islands",
    "Metropolitan Bank",
    "China Banking Corporation",
    "Security Bank",
    "Landbank of the Philippines",
    "PNB",
  ],
  "Vietnam": [
    "Vietcombank",
    "BIDV",
    "Agribank",
    "Techcombank",
    "MB Bank",
    "VIB",
    "ACB",
  ],
  "Pakistan": [
    "State Bank of Pakistan",
    "National Bank of Pakistan",
    "Habib Bank",
    "United Bank Limited",
    "Bank of Punjab",
    "MCB Bank",
    "HBL",
  ],
  "Bangladesh": [
    "Sonali Bank",
    "Janata Bank",
    "Agrani Bank",
    "BRAC Bank",
    "Dutch Bangla Bank",
    "Islami Bank Bangladesh",
    "Southeast Bank",
  ],
  "New Zealand": [
    "ANZ New Zealand",
    "Westpac New Zealand",
    "BNZ",
    "ASB Bank",
    "Kiwibank",
    "TSB Bank",
    "SBS Bank",
  ],
  "Greece": [
    "National Bank of Greece",
    "Alpha Bank",
    "Eurobank",
    "HSBC Bank plc",
    "Citibank Greece",
  ],
  "Nigeria": [
    "Zenith Bank",
    "Guarantee Trust Bank",
    "First Bank of Nigeria",
    "Access Bank",
    "FCMB",
    "Stanbic IBTC",
    "UBA",
    "Fidelity Bank",
  ],
  "Kenya": [
    "Kenya Commercial Bank",
    "Equity Bank",
    "Diamond Trust Bank",
    "Co-operative Bank",
    "Standard Chartered Kenya",
    "ABSA Bank Kenya",
    "National Bank of Kenya",
  ],
  "South Africa": [
    "ABSA Bank",
    "FirstRand Bank",
    "Standard Bank",
    "Investec Bank",
    "Capitec Bank",
    "Nedbank",
    "Bank of Athens",
  ],
  "Egypt": [
    "National Bank of Egypt",
    "Banque Misr",
    "Arab African International Bank",
    "Commercial International Bank",
    "ADIB Egypt",
    "Suez Canal Bank",
  ],
  "Ghana": [
    "Ghana Commercial Bank",
    "Ecobank Ghana",
    "Zenith Bank Ghana",
    "Stanbic Bank Ghana",
    "Barclays Bank Ghana",
    "Standard Chartered Ghana",
    "GCB Bank",
    "Access Bank Ghana",
  ],
  "Cameroon": [
    "Société Générale Cameroun",
    "Standard Chartered Bank Cameroon",
    "Ecobank Cameroun",
    "BMCE Bank Cameroon",
    "Banque International du Cameroun pour l'Épargne et le Crédit",
    "Credit Suisse Cameroon",
  ],
  "Côte d'Ivoire": [
    "Ecobank Côte d'Ivoire",
    "BICICI",
    "Standard Chartered Côte d'Ivoire",
    "Société Générale Côte d'Ivoire",
    "BMCE Bank Côte d'Ivoire",
    "Bank of Africa",
  ],
  "Ethiopia": [
    "Commercial Bank of Ethiopia",
    "Development Bank of Ethiopia",
    "Addis International Bank",
    "Dashen Bank",
    "Lion International Bank",
    "Nib International Bank",
    "Cooperative Bank of Oromia",
  ],
  "Tanzania": [
    "National Bank of Tanzania",
    "Tanzania Postal Bank",
    "Barclays Bank Tanzania",
    "Standard Chartered Tanzania",
    "Crdb Bank",
    "Equity Bank Tanzania",
    "Ecobank Tanzania",
  ],
  "Uganda": [
    "Bank of Uganda",
    "Barclays Bank Uganda",
    "Standard Chartered Uganda",
    "Stanbic Bank Uganda",
    "DFCU Bank",
    "Equity Bank Uganda",
    "Ecobank Uganda",
  ],
  "Zambia": [
    "Zambia National Bank",
    "Stanbic Bank Zambia",
    "Standard Chartered Zambia",
    "Barclays Bank Zambia",
    "Ecobank Zambia",
    "First National Bank Zambia",
    "Investrust Bank",
  ],
  "Zimbabwe": [
    "Reserve Bank of Zimbabwe",
    "First Capital Bank",
    "CBZ Bank",
    "Barclays Bank Zimbabwe",
    "Standard Chartered Zimbabwe",
    "Stanbic Bank Zimbabwe",
    "ZB Financial Holdings",
  ],
  "Angola": [
    "Banco Nacional de Angola",
    "Banco Angolano de Investimentos",
    "BIC",
    "Banco de Poupança e Crédito",
    "Standard Bank Angola",
    "Banco Comercial Angolano",
  ],
  "Mozambique": [
    "Bank of Mozambique",
    "Standard Bank Mozambique",
    "Banco Internacional de Moçambique",
    "Moza Bank",
    "Standard Chartered Mozambique",
    "Barclays Bank Mozambique",
  ],
  "Madagascar": [
    "Bank of Africa Madagascar",
    "BNI Credit Lyonnais",
    "SBM (Société Bancaire de Madagascar)",
    "Banque Malgache de Crédit",
    "AKF Bank",
  ],
  "Mauritius": [
    "Bank of Mauritius",
    "Mauritius Commercial Bank",
    "State Bank of Mauritius",
    "Barclays Bank Mauritius",
    "Standard Chartered Mauritius",
    "SBM Bank",
    "ABC Bank",
  ],
  "Senegal": [
    "BCEAO (Central Bank)",
    "Banque de l'Habitat du Sénégal",
    "Ecobank Senegal",
    "Banque International pour le Commerce et le Placement",
    "Bank of Africa Senegal",
    "Société Générale Senegal",
  ],
  "Morocco": [
    "Bank Al-Maghrib",
    "Banque Centrale Populaire",
    "Crédit Agricole du Maroc",
    "Attijari Bank",
    "BMCE Bank",
    "Banque Marocaine pour le Commerce et l'Investissement",
  ],
  "Tunisia": [
    "Central Bank of Tunisia",
    "Banque Nationale de Tunisie",
    "Banque Internationale Arabe de Tunisie",
    "Société Tunisienne de Banque",
    "Union Internationale de Banques",
    "Banque de Tunisie",
  ],
  "Algeria": [
    "Bank of Algeria",
    "Banque Nationale d'Algérie",
    "Banque Extérieure d'Algérie",
    "Crédit Populaire d'Algérie",
    "BADR Bank",
    "Banque de Développement Local",
  ],
  "Libya": [
    "Central Bank of Libya",
    "National Oil Corporation Bank",
    "Libyan Foreign Bank",
    "Libyan Arab Foreign Bank",
    "Wahda Bank",
    "Gumhouria Bank",
  ],
  "Sudan": [
    "Bank of Sudan",
    "Sudanese Banks Federation",
    "Faisal Islamic Bank",
    "Omdurman National Bank",
    "Agricultural Bank of Sudan",
    "Industrial Development Bank",
  ],
  "Botswana": [
    "Bank of Botswana",
    "First National Bank Botswana",
    "Barclays Bank Botswana",
    "Standard Chartered Botswana",
    "Stanbic Bank Botswana",
    "African Banking Corporation",
  ],
  "Namibia": [
    "Bank of Namibia",
    "First National Bank Namibia",
    "Standard Bank Namibia",
    "Nedbank Namibia",
    "Windhoek Capital",
    "Land Bank of Namibia",
  ],
  "Malawi": [
    "Reserve Bank of Malawi",
    "Standard Bank Malawi",
    "Ecobank Malawi",
    "First National Bank Malawi",
    "NBS Bank",
    "Finance Bank",
  ],
  "Rwanda": [
    "National Bank of Rwanda",
    "Bank of Kigali",
    "Equity Bank Rwanda",
    "Ecobank Rwanda",
    "KCB Bank Rwanda",
    "BPR Bank",
  ],
  "Burundi": [
    "Bank of the Republic of Burundi",
    "Banque du Crédit de Bujumbura",
    "Ecobank Burundi",
    "Interbank Burundi",
    "COGEBANK",
  ],
  "Democratic Republic of Congo": [
    "National Bank of Congo",
    "Banque Congolaise",
    "BIAC (Banque Internationale Africaine de Commerce)",
    "Ecobank DRC",
    "Bank of Africa DRC",
  ],
  "Republic of Congo": [
    "Bank of Congo",
    "Ecobank Congo",
    "BICEC (Banque Internationale de Crédit)",
    "Banque Gabonaise de Développement",
    "Bank of Africa Congo",
  ],
  "Sierra Leone": [
    "Bank of Sierra Leone",
    "Sierra Leone Commercial Bank",
    "Standard Chartered Sierra Leone",
    "Ecobank Sierra Leone",
    "Rokel Commercial Bank",
  ],
  "Liberia": [
    "Central Bank of Liberia",
    "Liberian Bank for Development and Investment",
    "EcoBank Liberia",
    "Standard Chartered Liberia",
    "International Bank Liberia",
  ],
  "Guinea": [
    "Central Bank of Guinea",
    "Banque Nationale de la Guinée",
    "Ecobank Guinea",
    "BMCE Bank Guinea",
    "Bank of Africa Guinea",
  ],
  "Mali": [
    "Central Bank of Mali",
    "Banque Malienne de Crédit et de Dépôts",
    "Ecobank Mali",
    "BMCE Bank Mali",
    "Bank of Africa Mali",
  ],
  "Burkina Faso": [
    "Central Bank of West African States",
    "Banque de l'Habitat du Burkina",
    "Ecobank Burkina Faso",
    "Banque Internationale du Burkina",
    "Standard Chartered Burkina",
  ],
  "Niger": [
    "Central Bank of Niger",
    "Banque de l'Habitat du Niger",
    "Ecobank Niger",
    "Bank of Africa Niger",
    "BMCE Bank Niger",
  ],
  "Togo": [
    "Central Bank of Togo",
    "Banque de l'Habitat du Togo",
    "Ecobank Togo",
    "Bank of Africa Togo",
    "Atlantic Bank Togo",
  ],
  "Benin": [
    "Central Bank of Benin",
    "Banque de l'Habitat du Benin",
    "Ecobank Benin",
    "Bank of Africa Benin",
    "BMCE Bank Benin",
  ],
  "Gabon": [
    "Bank of the States of Central Africa",
    "BGFI Bank Gabon",
    "Ecobank Gabon",
    "Banque Gabonaise de Développement",
    "Société Générale Gabon",
  ],
  "Equatorial Guinea": [
    "Bank of Central African States",
    "Ecobank Equatorial Guinea",
    "Banque des États de l'Afrique Centrale",
    "CCEI Bank",
  ],
  "Chad": [
    "Bank of Central African States",
    "Banque Tchadienne de Développement",
    "Ecobank Chad",
    "Banque Sahel-Sahara",
  ],
  "Seychelles": [
    "Central Bank of Seychelles",
    "Seychelles Commercial Bank",
    "Bank of Seychelles",
    "BCEL Bank",
    "Mauritius Commercial Bank Seychelles",
  ],
};

export function getCountries(): string[] {
  return Object.keys(banksData).sort();
}

export function getBanksByCountry(country: string): string[] {
  return banksData[country] || [];
}
